import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <p>Hi I'm</p>
      <h1 className="text-3xl ml-10 mr-10 font-serif font-bold ">
      <Image
          src="/jason_waving.jpg"
          alt="Hero Image"
          height={150}
          width={150}
          className="absolute bz-0 rounded-b-full rounded-t-full"
        />
          Jason_Nutt <a className={styles.title} href="">[a] MERN Developer!</a>
         
        </h1>

        <p className={styles.description}>
          I build most projects with <code className={styles.code}>Next.js {' '}</code> &
          <code className={styles.code}>MongoDB.</code>
          I have studied  <code className={styles.code}>javascript HTML5 CSS3 React/Next.js {' '}</code> &
          <code className={styles.code}>MongoDB</code>
          in various platforms & built with the Technologies that were the most intuitive to me and had the most opportunity for me to grow.
          <code className={styles.code}>FrontEnd Tech Degree from Team Treehouse {' '}</code>
          <code className={styles.code}>Currently Attending MongoDB University{' '}</code>
        </p>
        <code className={styles.code}>Here are a few things I have built for Small Businesses & side projects{' '}</code>
        

        <div className={styles.grid}>
          <a href="" className={styles.card}>
            <h2>Project 1 &rarr;</h2>
            <Image
          src="/jason_waving.jpg"
          alt="Hero Image"
          height={150}
          width={150}
          className="absolute bz-0 rounded-b-full rounded-t-full"
        />
            <p>This will be my favorite project. Most likely the E-Store or the Character app</p>
          </a>

          <a href="" className={styles.card}>
            <h2>Project 2 &rarr;</h2>
            <Image
          src="/jason_waving.jpg"
          alt="Hero Image"
          height={150}
          width={150}
          className="absolute bz-0 rounded-b-full rounded-t-full"
        />
            <p>This will be my 2nd favorite project. Mayb e the animations all in one</p>
          </a>

          <a
            href=""
            className={styles.card}
          >
            <h2>Project 3 &rarr;</h2>
            <Image
          src="/jason_waving.jpg"
          alt="Hero Image"
          height={150}
          width={150}
          className="absolute bz-0 rounded-b-full rounded-t-full"
        />
            <p>This will hold the Site I'm making for Emily Griffith right now for Pet Sitting.</p>
          </a>

          <a
            href=""
            className={styles.card}
          >
            <h2>Project 4 &rarr;</h2>
            <Image
          src="/jason_waving.jpg"
          alt="Hero Image"
          height={150}
          width={150}
          className="absolute bz-0 rounded-b-full rounded-t-full"
        />
            <p>
              I'll put the alternate project that I did not use for Project 1 in here
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
